# Generated by Django 4.2.7 on 2023-11-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0004_alter_order_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='urls',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('1', 'Web Developement'), ('2', 'Mobile App Developement'), ('3', 'Algorithms')], default='1', max_length=50),
        ),
        migrations.DeleteModel(
            name='OrderCategory',
        ),
    ]
