# Generated by Django 4.2.7 on 2023-11-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmer',
            name='tech_stack',
        ),
        migrations.AddField(
            model_name='programmer',
            name='specialization',
            field=models.CharField(choices=[('1', 'Front-End Developer'), ('2', 'Backend-Developer'), ('3', 'Full Stack Developer')], default='1', max_length=250),
        ),
    ]
