# Generated by Django 4.2.7 on 2023-11-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmerapp', '0002_remove_programmer_tech_stack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='profile_pic',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
